name: Remote Dispatch Action (Repository B)

on:
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.ACCESS_TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/dispatches \
            -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'