name: Workflow B (Pong)
on:
  workflow_call:
    inputs:
      ping:
        required: true
        type: string

jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - name: Pong
        run: echo "${{ inputs.ping }}"